{{- if .Values.global.createSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "discord-rag-bot.fullname" . }}-secrets
  labels:
    {{- include "discord-rag-bot.labels" . | nindent 4 }}
stringData:
  {{- range $k, $v := .Values.global.secretEnv }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}

